project_id = "afxwqkrneraatgovhpkb"

[auth.email.template.recovery]
subject = "Redefinir sua senha - Creator"
content_path = "./email-templates/reset-password.html"

[functions.check-subscription]
verify_jwt = true

[functions.migrate-users]
verify_jwt = true

[functions.migrate-brands]
verify_jwt = true

[functions.migrate-personas]
verify_jwt = true

[functions.migrate-strategic-themes]
verify_jwt = true

[functions.generate-plan]
verify_jwt = true

[functions.generate-quick-content]
verify_jwt = true

[functions.review-image]
verify_jwt = true

[functions.review-caption]
verify_jwt = true

[functions.review-text-for-image]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.generate-video]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.generate-caption]
verify_jwt = true

[functions.edit-image]
verify_jwt = false

[functions.revise-caption-openai]
verify_jwt = true

[functions.deactivate-account]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.platform-chat]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.send-reset-password-email]
verify_jwt = false

[functions.rd-station-integration]
verify_jwt = true

[functions.redeem-coupon]
verify_jwt = true
